from os import path
from re import findall, DOTALL


def get_icon_maps(directory, filepaths: list[dict[str, str]]) -> dict[str,dict[str,dict[str,str|int]]]:
    data = {}
    for item in filepaths:
        version: str = item['version']
        item_path: str = item['path']
        
        full_path: str = path.join(directory, version, item_path)

        with open(full_path, 'r') as file:
            content = file.read()
            file.close()

        data[version] = parse_lua_file(content)
    return data


# Generated by ChatGPT (regex looks like magic to me),
# then slightly modified to fix some issues
def parse_lua_file(file_content: str) -> dict[str,dict[str,str|int]]:
    data: dict = {'1x': {}, '2x': {}, '3x': {}}

    # Define a regex pattern to match the asset blocks for each size
    pattern = r"function make_assets_(\dx)\(\).*?(\{.*?\}) end"
    matches = findall(pattern, file_content, DOTALL)
    
    # Iterate over the matches to extract the data
    for size, block in matches:
        # Find all the icon definitions within the block
        icon_pattern = r"\['([^']+)'\] = \{ ImageRectOffset = Vector2\.new\((\d+), (\d+)\), ImageRectSize = Vector2\.new\((\d+), (\d+)\), ImageSet = '([^']+)' \}"

        icons = findall(icon_pattern, block)
        
        for icon in icons:
            icon_name, x, y, w, h, img_set = icon
            data[size][icon_name] = {
                'set': img_set,
                'x': int(x),
                'y': int(y),
                'w': int(w),
                'h': int(h)
            }
    return data