from .info import NAME, VERSION, DISCORD, REPOSITORY, WIKI, RELEASES, LATEST_RELEASE, MOD_GENERATOR_DOCUMENTATION
from .licenses import LICENSES, License
from .contributors import CONTRIBUTORS, FEATURE_SUGGESTIONS, SPECIAL_THANKS, Contributor

class ProjectData:
    NAME: str = NAME
    VERSION: str = VERSION
    DISCORD: str = DISCORD
    REPOSITORY: str = REPOSITORY
    WIKI: str = WIKI
    RELEASES: str = RELEASES
    LATEST_RELEASE: str = LATEST_RELEASE
    MOD_GENERATOR_DOCUMENTATION: str = MOD_GENERATOR_DOCUMENTATION
    LICENSES: list[License] = LICENSES
    CONTRIBUTORS: list[Contributor] = CONTRIBUTORS
    FEATURE_SUGGESTIONS: list[Contributor] = FEATURE_SUGGESTIONS
    SPECIAL_THANKS: list[Contributor] = SPECIAL_THANKS