# Generated by ChatGPT, based on https://stackoverflow.com/a/67019370

from PIL import Image
import numpy as np


def create_gradient_image(size: tuple[int, int], color1, color2, angle: int) -> Image.Image:
    angle -= 90
    width, height = size
    color1 = color1[:3]
    color2 = color2[:3]

    x, y = np.meshgrid(np.linspace(0, 1, width), np.linspace(0, 1, height))
    angle_rad = np.radians(angle)

    gradient = np.cos(angle_rad) * x + np.sin(angle_rad) * y
    gradient = (gradient - gradient.min()) / (gradient.max() - gradient.min())
    gradient = np.expand_dims(gradient, axis=-1) * (np.array(color2) - np.array(color1)) + np.array(color1)

    gradient = gradient.astype(np.uint8)
    return Image.fromarray(gradient)