name: Build and Upload (CI)

on:
  push:
    branches:
      - main
      - version-*

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check for build/ci-build.py
        run: |
          if [ ! -f build/ci-build.py ]; then
            echo "Warning: build/ci-build.py not found!"
            exit 1
          fi
        shell: bash

      - name: Set up Python 3.12.4
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'

      - name: Install Dependencies
        run: python -m pip install --upgrade pip && python -m pip install --upgrade pyinstaller

      - name: Run Build Script (build/ci-build.py)
        run: python build/ci-build.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kliko's modding tool
          path: build/bin/Kliko's modding tool.exe
